apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lars-sandbox
commonLabels:
  app: mess

resources:
- ./daemonset.yaml
- ./clusterrolebindings/mess-allow-nodes-rb.yaml
- ./clusterroles/mess-allow-nodes.yaml
- ./roles/mess-controller.yaml
- ./serviceaccount.yaml
- ./rolebindings/mess-allow-privileged.yaml
- ./rolebindings/mess-controller.yaml
- ./crd.yaml
