apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mess-controller
rules:
- apiGroups:
  - "mess.massopen.cloud"
  resources:
  - messconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
