apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mess-allow-messconfigs
rules:
- apiGroups:
  - "mess.massopen.cloud"
  resources:
  - messconfigs
  verbs:
  - get
  - list
  - watch
